server:
  port: 8080
spring:
  flyway:
    enabled: true
    schemas: Dollar
    user: postgres
    password: postgres
    locations: classpath:db.migrations
  datasource:
    url: jdbc:postgresql://postgres:5432/database
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: Dollar
        jdbc:
          lob:
            non_contextual_creation: true
eureka:
  instance:
    appname: currency-service
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka



