server:
  port: 8081
spring:
  flyway:
    enabled: true
    schemas: Weather
    user: postgres
    password: postgres
    locations: classpath:db.migration
  datasource:
    url: jdbc:postgresql://postgres:5432/database
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: Weather
        jdbc:
          lob:
            non_contextual_creation: true
weather:
  token: e5954aa2cd4b44a8a10181807202211
eureka:
  instance:
    appname: weather-service
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka
