apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      name: eureka
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: eureka:1.0.0
          imagePullPolicy: IfNotPresent


#  eureka:
#    image: "eureka:1.0.0"
#    ports:
#      - "8761:8761"