server:
  port: 8082
weather:
  url: http://localhost:8081
currency:
  url: http://localhost:8080
eureka:
  instance:
    appname: prediction-service
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka
